name: Deploy Angular a Netlify

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular app (usando npx)
        run: npx ng build --configuration production

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy a Netlify 
        run: netlify deploy --dir=dist/md-front/browser --prod 
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLYFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}